services:

  sonarqube:
      image: sonarqube:latest
      container_name: plh-sonarqube
      environment:
        SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      ports:
        - "9000:9000"

  judge-dredd:
    build:
      context: /src/JudgeDredd
      dockerfile: Dockerfile
    container_name: plh-judgedredd
    ports:
      - "5005:8080"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: plh-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: somew0rds
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: plh-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres

  minio:
    container_name: plh-minio-server
    image: minio/minio:latest
    ports:
      - "9008:9000"
      - "9009:9001"
    volumes:
      - minio_data:/home/storage/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data    
    
  vault:
    image: hashicorp/vault:latest
    container_name: plh-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_DEV_LISTEN_ADDRESS : "vault:8200"
    privileged: true

volumes:
  postgres_data:
  minio_data:  
  localstack_data:  