@LighthouseSocial.WebApi_HostAddress = http://localhost:5072

### Create a new lighthouse
POST {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse
Content-Type: application/json

{
  "name": "Cape Espichel",
  "countryId": 42,
  "latitude": 38.533,
  "longitude": 9.12
}

###

### Update an existing lighthouse
PUT {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/8876b947-4a51-4a94-824a-519c389e0bf8
Content-Type: application/json

{
  "name": "Cape Espichel Updated",
  "countryId": 42,
  "latitude": 38.533,
  "longitude": 9.12
}

###

### Delete a lighthouse
DELETE {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/027f1bb3-4ff9-4aa5-888d-815da7478c5e
Accept: application/json

###

### Get Lighthouse by ID
GET {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/8876b947-4a51-4a94-824a-519c389e0bf8
Accept: application/json

###

### Get Photos for a Lighthouse
GET {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/10000000-0000-0000-0000-000000000001/photos
Accept: application/json

###

### Get Top 3 Lighthouses
GET {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/top/3
Accept: application/json

###

### Get Top 5 Lighthouses
GET {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/top/5
Accept: application/json

###

### Get Top 10 Lighthouses
GET {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/top/10
Accept: application/json

###

### Get Lighthouses by page
GET {{LighthouseSocial.WebApi_HostAddress}}/api/lighthouse/paged?page=2&pageSize=3
Accept: application/json

###